### ISSUE TITLE
netcdf.open and netcdf4.open broken in master branch

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#132]
Trying to open a netcdf file from the master branch results in a `TypeError` message, such as:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pygeode/formats/netcdf.py", line 391, in open
    return finalize_open(dataset, dimtypes, namemap, varlist, cfmeta)
  File "pygeode/formats/__init__.py", line 266, in finalize_open
    dataset = cf.decode_cf(dataset, ignore=list(dimtypes.keys()))
  File "pygeode/formats/cfmeta.py", line 335, in decode_cf
    for auxname in _anc.split(' '):
TypeError: a bytes-like object is required, not 'str'
```
or
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pygeode/formats/netcdf.py", line 391, in open
    return finalize_open(dataset, dimtypes, namemap, varlist, cfmeta)
  File "pygeode/formats/__init__.py", line 266, in finalize_open
    dataset = cf.decode_cf(dataset, ignore=list(dimtypes.keys()))
  File "pygeode/formats/cfmeta.py", line 383, in decode_cf
    if (_st == 'time' or cls == TAxis or _units.startswith('days since') or _units.startswith('hours since') or _units.startswith('minutes since') or _units.startswith('seconds since')) and ' since ' in _units:
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
It seems to stem from the changes made in f78c2f4a879c7d6c1cb02784df6fcebf90d1db39.  Reverting this change circumvents the problem.  Does not affect the latest release (1.3.0), so not a critical bug yet.  However, it's causing the CI status to report a failed state (`var_test` is failing in the serialization test when writing to netcdf and reading back again).

**Comment by aph42** [comment]
I'm assuming this is an issue in python3.8? The previous commit was intended to handle unicode strings in netcdf files (I have some Chinese postdocs who have given me netcdf files with attributions in unicode). The tests pass for me in a python 3.7 environment.

**Comment by aph42** [comment]
Whoops - I lied. My version of nosetests was hardwired to use python 2.7. I'm getting the same issue now, I think.

**Comment by aph42** [comment]
This is now fixed in python 2 and 3.7 on my local machine.

**Comment by neishm** [comment]
Nice!  Everything's working on my end, too.  Travis-CI is still failing, but for an unrelated reason (It's trying to test on a beta version of Python 3.9, which doesn't have a binary wheel for netcdf4 yet).  The attribute tests are all okay.
